### ISSUE TITLE
作者、贡献者报到帖

### ISSUE THREAD

**Issue by yihui** [cosname/rmarkdown-guide#1]
大家都来报个到吧，如果不介意的话，自我介绍一下（帖子是公开的，所以涉及个人隐私的就不要写出来了），尤其是自己的特长、写作经验、以及对 R Markdown 的熟悉程度。

我是始作俑者，可能就不需要过多介绍了。动机是[如我在一次报告摘要中所说](https://mp.weixin.qq.com/s/X4DRfh1hP20vLBi0t9U4hg)，希望在中文世界里能有一本本土作者用本土语言结合自己实战经验写出来的 R Markdown 主题书。这本书我没想以作者的身份参与，因为我几乎不可能有这么多时间。我在这件事中的身份只是协助者，尤其是有什么 R Markdown 相关的问题要是不清楚我可以来解答，由你们把答案展开写到书里。

感觉有需要我的时候请 `@yihui` 或在右边 `Assignees` 里面加我。

楼下继续。

**Comment by rucwyf** [comment]
大家好，我是王祎帆，是中国人民大学统计学院的博士生，也是统计之都的一份子，用R和Rmd大概有2-3年经验了，用Rmd方面主要是用它给课程作业排版，对于它的其他应用，也希望能够一边学习一边和大家合作写这本书。

之前参与了<R Graphics Cookbook> 的第二版的翻译工作，算是有一些经验，看到谢师兄让我当领队有点受宠若惊。。。如果大家有更有经验 & 更想当的随时欢迎替掉我！如果最后还是我的话也会认真负责的~

**Comment by yihui** [comment]
@rucwyf 来，请你开始烧第一把火：新开个 Github 事项讨论一下大纲吧，收集一下大家的想法。

**Comment by gaospecial** [comment]
我来报个到，我现在是[热心肠研究院](http://www.mr-gut.cn)的数据科学家，说起来用R也有2-3年的历史了，建了一个[blogdown小站](http://r.bio-spring.info)（但是也好久没更新了）。日常工作中，我会用 Rmd 出一些数据分析报表，感觉能不能升职加薪跟 Rmd 水平密切相关的。如果有中文书那真是太好了，为此不惜班门弄斧。

**Comment by enixam** [comment]
大家好我是闫求识, 是中国传媒大学数据新闻专业的大四学生。平时经常用 rmd 做一些知识记录和数据分析的小项目, 希望和大家多学习~

**Comment by daijiang** [comment]
大家好，我是李代江。我用 Rmarkdown 有 5-6 年了，主要是用来写学术论文。我即将开始在[新单位的工作](https://www.lsu.edu/science/biosci/faculty_and_staff/li.php)，所以应该是没有什么时间来写稿了。但是我非常乐意时不时地来看看稿子提提意见。

**Comment by korsakowii** [comment]
报到～大家好我是闫晓雨，南加州大学生物统计硕士，今年毕业。
主要使用R和Rmd用于课程作业的分析与排版，也做过幻灯片来介绍模型包，正在尝试嵌入Shiny做交互式文档。
目测即将失业，因此有空反思总结所学，探索未来发展方向。
向各位学习～

**Comment by dipterix** [comment]
求问下这本书的开发进程是怎样的，有哪些人可以参与编写呢？我从Github推荐上看到顺道过来了，所以不是很清楚。

**Comment by enixam** [comment]
> 
> 
> 求问下这本书的开发进程是怎样的，有哪些人可以参与编写呢？我从Github推荐上看到顺道过来了，所以不是很清楚。

目前刚开始创作, 处于八字没一撇阶段 =.= 欢迎贡献想法

**Comment by liangliangzhuang** [comment]
大家好，我是庄亮亮（庄闪闪），也是公众号[庄闪闪的R语言手册]的小编。现在是在读的应用统计研究生，使用R5年了吧？去年寒假整理了一波1.5w字的推文[Rmarkdown入门教程](https://mp.weixin.qq.com/s/JD9dWA6OnEOwi4WpJ_t4Qg)和在b站录制了对应的[教学视频](https://www.bilibili.com/video/BV1ib4y1X7r9)，个人感觉效果还算可以吧。但是内容确实非常基础，只适合入门学习，和写书还差远了。不过作为一名R爱好者以及Rmarkdown的爱好者，希望加入这个队伍，努力学习，做出一点贡献。

**Comment by yihui** [comment]
@liangliangzhuang 欢迎欢迎！推文扩展一下也可以成书的。
