### ISSUE TITLE
大纲讨论

### ISSUE THREAD

**Issue by rucwyf** [cosname/rmarkdown-guide#4]
大家好，欢迎提出任何关于大纲的想法。先贴上谢师兄的三个作品，以供参考
[《R Markdown 参考》](https://bookdown.org/yihui/rmarkdown)
[《R Markdown 实例》]( https://bookdown.org/yihui/rmarkdown-cookbook)
[《R语言忍者秘笈》]( https://bookdown.org/yihui/r-ninja/auto-report.html )

不好意思最近在外面旅游，等回去了再结合大家的想法给出一个汇总的提纲~

**Comment by yihui** [comment]
你自己可以先讲讲你的想法。

**Comment by enixam** [comment]
有一个想法是: 是否可以在简要介绍完 Markdown 和 R Markdown 的基础知识后, 添加一个类似展览柜的章节, 展示一下不同输出格式做的比较酷的范例 (交互 html, pdf 报告, 网站, 幻灯片, ...), 然后分别导向后面的不同章节。一方面给人一种目标感, 展示了 R Markdown 的可能性, 另一方面也节省有差异化需求的读者的时间

**Comment by gaospecial** [comment]
我觉得可以从读者角度考虑，首先面对rmarkdown小白讲讲基础知识，谈谈knitr的情怀，吸引无知少年跳坑，成为入门小白；其次，针对入门小白特别愿意接触炫酷技术的心理，开设一点类似于“一份文档N份不同格式输出”的操作案例，让他们欲罢不能，砥砺前行；最后，到了真正表演技术的时刻，详细解读不同输出格式的可选操作、文档的配置、模板的打造等等，让你从此游刃有余；特别地，如果还有精力的话，不妨涉及一下rmarkdown扩展的开发知识，从此成为自己人。

综上所述，同意楼上 @enixam 的意见！

**Comment by gaospecial** [comment]
刚刚注意到 @yihui  的《现代统计图形》杀青了。这本书是否也会像前辈如此优秀？

**Comment by dipterix** [comment]
大家可以考虑下国内现在使用rmarkdown的人群是怎样的。个人觉得有这么几个问题需要思考下
1. 国外很多人是会用markdown或者latex的，而不是不仅仅是需要写论文的人，向rmarkdown或者knitr转型相对比较容易。而且母语是英语的人感觉掌握起来快很多，所以要考虑下怎样让英语不是很好的用户更快的接受
2. R语言的使用者在国外已经开始变得多元起来了，大概是从2015年左右之间有一波风口，这个 @yihui 更了解。可能需要挖掘下国内用户的需求：不仅仅是作为学生的需求，而是作为学生可能未来十几年在职场的需求。比方说现在美国很多公司要求会Excel跟VBA，只是因为上一代公司在创建的时候很多模型的架构就是用VBA写的，而这些模型的编写人之前在学校被训练的就是Excel跟VBA。所以可以考虑下现在工业界应用方面的痛点
3. 从编程习惯来讲，很多时候大家写R并不是像Python或者Java一样去了解内部构造，R上手很快，但是它的一些概念，比方说environment, generics, call/expression 很多人可能用了好几年都不会了解（感觉很多时候课程设置并没有很系统教编程），所以这本书的阅读对象可能并不是很了解R编程，个人建议是提供很多实用的例子，这样他们就能面向实例编程（CTRL+C & V）

至于顺序可以考虑上来在introduction直接展示一些精美的案例，附上对应章数跟cheatsheet，然后再讲安装，hello world，以及怎么从hello world演化到很复杂的文档结构（像是排版，布局，代码块渲染，Shiny交互式嵌套，dashboard，自定义模版等等）

**Comment by rucwyf** [comment]
不好意思耽搁地有点久了，我综合了一下大家的想法以及自己的一些构想，根据 [《R Markdown 实例》]( https://bookdown.org/yihui/rmarkdown-cookbook) 的主线草拟了一个中文版的章节，其中包含了一些 [《R Markdown 参考》](https://bookdown.org/yihui/rmarkdown) 里较为常用的内容，使本书更丰富。这只是一个初步的想法，有待和各位进一步探讨。

大家也可以在评论里说一下自己想要领取哪些章节的写作任务，根据现在的人数（貌似是四人？），**每人大概要分5章左右**，建议根据**兴趣 / 工作学习需求**来选择。

另外麻烦@enixam介绍一下如何进行写作，我看好像搭了一个bookdown的框架。

以下是大纲草稿：

## 第一部分：基础篇
### 第一章：概念介绍
- 注1：这一部分在英文版里是在“安装”的后面，但从逻辑上讲这样似乎更顺畅，待探讨【英文版第二章不仅包含了概念介绍，还包含了很多别的内容，可以融入之后的部分】
- 注2：可在谢师兄的基础上，用一些更“通俗”的话加强解释，
- 注3：@enixam和@gaospecial提出的“展览柜”，可以在这一部分进行，在第一章比在介绍完基础知识后给出更能吸引读者，待探讨

### 第二章：安装
### 第三章：基础操作
-  注：融入一些英文版第二章的内容
### 第四章：基础操作：文档元素
### 第五章：基础操作：排版
## 第二部分：输出“万花筒”
### 第六章：HTML 
- 注1：英文版中这一章在LaTeX后面，但我一开始学习的时候老师是从HTML讲起的，感觉对于中国学生来说可能从这里入手会比较简单，待探讨
- 注2：这一部分可以加入一些排版的R包，如“prettydoc”
### 第七章：LaTeX 
- 注：建议加入期刊排版案例，书的案例视情况而定，感觉受众不如期刊大，待探讨
### 第八章：Presentation
- 注1：英文版没有这一部分，可参考[《R Markdown 参考》](https://bookdown.org/yihui/rmarkdown)，其中我将第四章“Presentation”合并为PPT，章节名字可探讨
- 注2：英文版这一章在Word后面，但从我自己以及周围同学的使用频率上看，这一部分还是较多的，故将顺序进行了调整，待探讨
### 第九章：Word 
### 第十章：其他输出类型
- 注：英文版没有这一部分，可参考[《R Markdown 参考》](https://bookdown.org/yihui/rmarkdown)
### 第十一章：多种输出格式
## 第三部分：操作技巧
### 第十二章：表格操作
### 第十三章：代码块渲染
### 第十四章： Hooks
- 注1：这个“Hooks”没想好怎么翻译，感觉直接写英文反而会减小歧义，待探讨
- 注2：由于都是“Hooks”，故将英文版“Output Hooks”和“Chunk Hooks”合并，其合理性待探讨
### 第十五章：其他小技巧
## 第四部分：进阶操作
### 第十六章：与其他语言的结合
### 第十七章：Dashboards
- 注：可参考[《R Markdown 参考》](https://bookdown.org/yihui/rmarkdown)
### 第十八章：Shiny
### 第十九章：自定义排版
- 注1：可参考[《R Markdown 参考》](https://bookdown.org/yihui/rmarkdown)
- 注2：可加入 Tufte Handouts 的案例
## 第五部分：用 Rmd 开展工作
### 第二十章：管理项目
### 第二十一章：工作流
### 第二十二章：工业界？？
- 注：@dipterix ，我对工业界这边不是很了解，先根据英文版分了两章，可视情况增删

**Comment by enixam** [comment]
如何进行写作是指 bookdown 的基本操作吗？要不我录个视频简单演示一下。我也觉得像 Markdown 的语法, 安装包, 自定义 css 这种内容可以配一些视频辅助读者理解，不然概念性的内容可能有些无聊了

**Comment by rucwyf** [comment]
嗯嗯如果方便的话可以录个视频演示一下，另外在书里面加入视频这个也是可以的，到时候可以在写的时候标一下哪部分说不清楚，需要用视频来辅助，最后找一个人来录一下就行，保证视频的一致性。大家看这样可以吗？

**Comment by enixam** [comment]
这里有一个 bookdown 的简单介绍视频 ~ https://www.bilibili.com/video/BV1wV411m7Qu/

**Comment by gaospecial** [comment]
> 如何进行写作是指 bookdown 的基本操作吗？要不我录个视频简单演示一下。我也觉得像 Markdown 的语法, 安装包, 自定义 css 这种内容可以配一些视频辅助读者理解，不然概念性的内容可能

**Comment by rucwyf** [comment]
大家看有没有什么问题呢？或者有没有什么倾向写的章节~

**Comment by rucwyf** [comment]
大家看有没有什么问题呢？或者有没有倾向写的章节~@enixam @dipterix @gaospecial

**Comment by gaospecial** [comment]
> 大家看有没有什么问题呢？或者有没有倾向写的章节~@enixam @dipterix @gaospecial

@rucwyf 虽然 @yihui 说我们准备写一本全新的中文书，但是我思虑再三之后，觉得可能还是翻译 [rmarkdown-book](https://github.com/yihui/rmarkdown-cookbook) 是个不错的开始。

原因有四：

1. rmarkdown-book 本来具有完整的知识体系，是软件作者本人深思熟虑后的体现，我辈或难以逾越；
2. rmarkdown 不仅是一个软件包，更是一个庞大的生态体系，涉及 R、YAML、HTML、Javascript、CSS、OFFICE、PDF 等各方面的知识，目前来看，各方贡献者多仅了解其片面，尚未能整体把握并确保方向稳妥；
3. 就我自身而已，是抱着学习的态度参与本书贡献的，因为自己只掌握一点皮毛。曾经试图翻译 rmarkdown-book 未果，现在想借势再起呢。
4. rmarkdown-book 本身仍在不断进化中，如果有本中文译本紧跟不掉队，已经是善莫大焉。千万不要低估了这件事的难度，切切。

**Comment by rucwyf** [comment]
@gaospecial 如果我没理解错的话，你的意思是觉得我之前写的提纲是重新写是吗？

我之前写的那个其实就是[《R Markdown Cookbook》]( https://bookdown.org/yihui/rmarkdown-cookbook) 的翻译，目录是基本可以一一对上的，和原书不同的是我在内容顺序上做了一些调整，做出调整的部分都已经注明，并且根据大家的建议加入了 [《R Markdown 参考》](https://bookdown.org/yihui/rmarkdown) 的一些翻译性的章节（如Dashboard），实际写作时仍以翻译为主，需要自己创作的地方更多地集中在第一章，后面的部分主要就是翻译工作了。

不知道解释的是否正确？

**Comment by enixam** [comment]
抱歉最近学校事比较多，回复慢了。
我觉得即便我们想自由发挥，也很难跳出文档和 cookbook 这两本书的框架，它们涵盖的内容已经非常全面和事无巨细了。所以大思路上肯定和文档的框架没有什么区别。只是我们的最终目的不是翻译，如果有些自己独有的心得案例，或者觉得原书的表述 / 写作顺序可以优化的地方，完全可以先按自己的意见来。

**Comment by yihui** [comment]
我个人不太建议翻译。最好是看完后关上书，结合自己的经验来写，当然确实存在难以跳出这两本书框架的这样一个难点。

**Comment by rucwyf** [comment]
我感觉翻译和结合个人经验这两条线是相通的，大家可以在翻译的基础上加入个人理解的内容，如果对某一部分比较熟也可以先结合经验写，再翻译，毕竟这个工作不是写一遍就结束了，肯定会反过头来再修改，就像写论文一样，最后的成品和初稿肯定会有很大的不同，我的建议是先开始写作/翻译工作，慢慢体会。

**Comment by yihui** [comment]
嗯，这样也行。

**Comment by rucwyf** [comment]
感觉是不是可以进一步推动了，最近好像比较沉寂。。。大家对现有的方案如果有什么问题的话欢迎积极讨论！！！如果一直没有选择自己倾向于领取哪些章节的写作任务，我可能就要来分配了，DDL先定在10.20吧~

PS：大家有任何问题都尽量说出来，需要交流推进下去

@gaospecial @dipterix @enixam

**Comment by enixam** [comment]
先抢简单的，我先把前三章领了

**Comment by rucwyf** [comment]
看大家没啥反应。。。为了推动进程，我就先来给大家分下工作吧，都是根据大家的意愿以及提的建议来分的，整体上咱四个人一人负责一大块吧：

@enixam 1-5章
@gaospecial 6-11章
@rucwyf 12-15章
@dipterix 16-19章

剩下20章及以后的先放一下吧，大家有什么问题或者想法一定要在这里说，无论是遇到的代码问题还是对章节/写作方式有问题都要提出来，多交流才能更好地合作~

**Comment by dipterix** [comment]
@rucwyf 不好意思最近我不是很有时间，可能需要其他人来编写16-19章。

**Comment by rucwyf** [comment]
不好意思之前学校有点忙没来得及回复，@dipterix 我们先翻译着，你看情况来跟就行，实在不行我们翻译完了再分一分就好，如果可以的话可以尽量来翻译，其实所用时间并不是很多。

来问一下大家的进度如何？有没有碰到什么麻烦的地方？或者有没有一些翻译上的小trick可以分享？@enixam，@gaospecial，@dipterix？

- 我现在大概快翻译完12章了，目前的翻译方式是先看一遍谢大写的英文版，然后尝试复述 & 用自己的话来进行填补/扩充，如果一些部分自己拿捏不好的话可以直接翻译（但要**注意中文语义，不要出现病句**）；
- 代码部分我是在谢大的基础上直接使用/进行修改的（https://github.com/yihui/rmarkdown-cookbook），速度会快很多（巨人的肩膀）；
- 一个比较重要的地方在于**上下文一些说法的统一**，比如 "appearance" 如果前文翻译成 ”外观“，后文也要用相同的翻译，不要出现歧义，这个我在最后会再统一一下，但大家在自己部分翻译的时候也要注意这一个部分；
- 需要先在本地编译一下，确定自己写的部分能够编译再上传，在编译的时候为了速度，可以先把其它章节去掉。

目前一些小问题：
- 有些输出结果太长了，如果输出pdf格式的话就会超出去，这个有没有什么办法解决呢？

**Comment by gaospecial** [comment]
我还没有完成多少内容，唯一的进展可能是搭建了个骨架。@rucwyf 已经完成了一个章节，可喜可贺。不过我注意到你还没有一个 fork。关于如何在 GitHub 上协作，我日前整理了一个文档，放在 [这里：开始写作](https://github.com/gaospecial/rmarkdown-guide/blob/master/Start.md)，供大家参考。

**Comment by rucwyf** [comment]
> 我还没有完成多少内容，唯一的进展可能是搭建了个骨架。@rucwyf 已经完成了一个章节，可喜可贺。不过我注意到你还没有一个 fork。关于如何在 GitHub 上协作，我日前整理了一个文档，放在 [这里：开始写作](https://github.com/gaospecial/rmarkdown-guide/blob/master/Start.md)，供大家参考。

**Comment by rucwyf** [comment]
@gaospecial 好的非常感谢！我写好了就fork上去！翻译这边可以每天写一点，这本书每个小节的长度都不长。

**Comment by enixam** [comment]
目前完成第一章里面的宏观性介绍内容，和第二章的安装指导。

**Comment by rucwyf** [comment]
@gaospecial @enixam 大家进度如何啦？完成了的部分可以先fork上来，大家互相看一下风格的进度，有助于后面的统一也有助于互相督促。我之前已经发了一个requests了，大家可以看看有没有什么问题

**Comment by enixam** [comment]
> @gaospecial @enixam 大家进度如何啦？完成了的部分可以先fork上来，大家互相看一下风格的进度，有助于后面的统一也有助于互相督促。我之前已经发了一个requests了，大家可以看看有没有什么问题

现在基本完成了前三章 隔离结束后会把内容放上来:joy:

**Comment by rucwyf** [comment]
@gaospecial @enixam 又来咨询一下大家的进度~我看pull request好像有一点问题，以及部署在线预览的事还麻烦技术大佬 @enixam 看一下

**Comment by liangliangzhuang** [comment]
大家好，仔细看了大家的讨论@gaospecial @dipterix @rucwyf @enixam ，原来大家早就开始创作了。冒昧的问一下，不知道现在加入会不会太晚，最近@yihui和我说，我才知道（消息闭塞）。也不知道现在能不能帮上忙😨😂

我说一下我的一些想法：这是我前段时间做的有关R文档沟通的一些[推文](https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzI1NjUwMjQxMQ==&action=getalbum&album_id=1684900703049138178&scene=173&subscene=0&sessionid=1617943488&enterid=1617943498&from_msgid=2247493762&from_itemidx=1&count=3&nolastread=1#wechat_redirect)。

对于Rmarkdown的入门教程，我分成了6节。寒假闲暇时光也录制了对应的[视频](https://www.bilibili.com/video/BV1ib4y1X7r9)，每个视频剪辑成10min左右，在b站供需要的学生学习。

>  个人感觉视频教程会更好理解，以后自己也会多配合推文同时发布。学习效率翻倍！

# 1. markdown简介

## 1.1 Typora介绍

# 2. Rmarkdown简介 

## 2.1 官网介绍

## 2.2 参考资料

# 3. Rmarkdown流程演示

## 3.1 安装

## 3.2 新建Rmarkdown项目

## 3.3 markdown的导出

### 3.3.1 手动导出

### 3.3.2 命令行导出

## 3.4 Rstudio界面介绍

# 4 图、表和代码输出

# 4.1 代码输出

## 4.2 图片输出

## 4.3 表格输出

## 4.4 表格渲染

# 5. Rmarkdown的主题格式

# 6. 生成可重复性报告

具体可以看这个[推文](https://mp.weixin.qq.com/s/JD9dWA6OnEOwi4WpJ_t4Qg)，之后还对一些拓展进行介绍[写轮眼](https://mp.weixin.qq.com/s?__biz=MzI1NjUwMjQxMQ==&mid=2247489685&idx=1&sn=aa5bccb2afe9c3882d415e4ed17c5b48&chksm=ea24e771dd536e6788cf8689009c469150998b58d4673c0453876f9c3b9854dbae385af33a2b&scene=178&cur_album_id=1684900703049138178#rd)，[ppt](https://mp.weixin.qq.com/s?__biz=MzI1NjUwMjQxMQ==&mid=2247488738&idx=1&sn=b0d21bfe77d3c7c65d0c8df72c1694d0&chksm=ea24eb06dd536210b1d1ed44d2dcb5214d106a787ace6b437549a450a83300e84b052c595a5b&scene=178&cur_album_id=1684900703049138178#rd)，[beamer](https://mp.weixin.qq.com/s?__biz=MzI1NjUwMjQxMQ==&mid=2247488659&idx=1&sn=738cd20bfccf8936b5d969483d4f6891&chksm=ea24eb77dd536261e9cc68eac635d66113ea2e296d3b5ed6280410771c0b956be1af64f52eee&scene=178&cur_album_id=1684900703049138178#rd)等，之后的想法可能是加入[bookdown](https://mp.weixin.qq.com/s?__biz=MzI1NjUwMjQxMQ==&mid=2247492971&idx=1&sn=b342777e1f1bf1d4a85cff0f20735491&chksm=ea271a8fdd50939996772ee0a8e3bf1cb1f35b2361ef6c160011074464dc957a421e44cba1fe&scene=178&cur_album_id=1684900703049138178#rd)，blogdown(待)，thesisdown（待）的入门教程（争取把文档沟通做个系列出来）。

这是我前段时间本来想的一个思路，可以供大家参考下（比较初级）。

但是现在如果从写一本关于Rmarkdown的中文书来看，我的入门教程内容确实不够丰富（当时我的想法是，让大家了解Rmarkdown会套模板和简单的操作即可）。对@rucwyf提的提纲表示赞同，如果现在我还能出一点力的话，尽管给我安排任务。
😃

**Comment by rucwyf** [comment]
@liangliangzhuang 欢迎欢迎！目前@gaospecial @rucwyf @enixam正在稳步推进自己负责的部分（共1-15章），你可以主要负责16-19章，不过这个和你之前做的不太一样，有些挑战性。如果觉得有些困难的话也可以先看看在现有的基础上能不能把你的部分加入，比如一些排版的R包介绍以及一些表格的操作应该都是可以加入的。

我这边负责的基本快译完了，到时候一起传上来，看@gaospecial @enixam有没有需要@liangliangzhuang 帮忙的地方？

**Comment by rucwyf** [comment]
@liangliangzhuang 欢迎欢迎！目前@gaospecial @rucwyf @enixam正在稳步推进自己负责的部分（共1-15章），你可以主要负责16-19章，不过这个和你之前做的不太一样，有些挑战性。如果觉得有些困难的话也可以先看看在现有的基础上能不能把你的部分加入，比如一些排版的R包介绍以及一些表格的操作应该都是可以加入的。

我这边负责的基本快译完了，到时候一起传上来，看@gaospecial @enixam有没有需要@liangliangzhuang 帮忙的地方？

**Comment by liangliangzhuang** [comment]
好的，我先试试16-19章。

**Comment by gaospecial** [comment]
> 好的，我先试试16-19章。

亮闪闪快把你完成的内容 PR 上来。@liangliangzhuang

**Comment by liangliangzhuang** [comment]
> > 好的，我先试试16-19章。
> 
> 亮闪闪快把你完成的内容 PR 上来。@liangliangzhuang

刚已经把三章的初稿上传了（还需要大改）。 但是弱弱的说一句：我不是很清楚上传的方式对不对。
